- name: list of hash example
  hosts: dev
  user: ec2-user
  become: true
  tasks:
  - user:
     name: "{{ item.x }}"
     state: present
     group: "{{ item.y }}"
    with_items:
     - { x: 'ram', y: 'staff' }
     - { x: 'shyam', y: 'manager' }

