- name: example of facts
  hosts: dev
  vars:
    file_path: /etc/motd
  user: ec2-user
  become: true
  tasks:
  - name: print ip in motd file
    copy:
     content: "{{ ansible_eth0.ipv4.address }}"
     dest: "{{ file_path }}"

  - name: copy server os name and version
    lineinfile:
     line: "{{ ansible_distribution }}  and {{ ansible_distribution_major_version }}"
     dest: "{{ file_path }}"
     insertafter: BOF
