- name: nested loop example
  hosts: dev
  user: ansible
  become: true
  vars:
    mygroups:
     - staff
     - manager
     - teamlead
    myusers:
     - user1
     - user2
     - user3
  tasks:
  - name: create three group
    group: 
      name: "{{ item }}"
      state: present
    with_items:
     - "{{ mygroups }}"
  
  - name: create users
    user: 
      name: "{{ item[0] }}"
      state: present
      groups: "{{ item[1] }}"
      append: yes
    with_nested:
     - "{{ myusers }}"
     - "{{ mygroups }}"

