- name: list of hash example
  hosts: dev
  user: ec2-user
  become: true
  ignore_errors: true
  tasks:
  - name: start service
    service:
     name: "{{ item }}"
     state: stopped
    with_items:
     - postfix

  - name: check service status
    command: systemctl is-active postfix
    ignore_errors: yes
    register: svc

  - debug: var=svc

  - name: start postfix service if it is stopped.
    service:
      name: postfix
      state: started
    when: svc.stdout == "inactive"

