- name: list of hash example
  hosts: dev
  user: ansible
  become: true
  tasks:
  - name: create application path 
    file:
      path: "{{ app_path }}"
      state: directory

  - name: copy main.cf file in "{{ app_path }}"
    copy:
      src: /etc/postfix/main.cf
      dest: "{{ app_path }}"

  - name: print variable application version
    debug:
      msg: " Application version is {{ app_version }} "
